### ISSUE TITLE
(ge)ev  [real/complex variant that only computes eigenvalues]

### ISSUE THREAD

**Issue by tkloczko** [michael-lehn/FLENS#13]
Hi dear Michael,

We met a problem using the real variant of the ev method that only computes eigenvalues (flens/lapack/ge/ev.tcc line 1359). In fact, this function redirects only to the complex variant with temporary workspace.

We corrected it by separating the real and the complex version, this latter being unchanged except for the restrictions. We wrote the real variant as follows:

``` c++
template <typename MA, typename VW>
typename RestrictTo<(IsRealGeMatrix<MA>::value
                  && IsRealDenseVector<VW>::value),
         typename RemoveRef<MA>::Type::IndexType>::Type
ev(MA       &&A,
   VW       &&w)
{
    typedef typename RemoveRef<VW>::Type VWT;
    VWT wi;

    return ev(false, false, A, w, wi, A, A);
}
```

Maybe, we misuse the method, if so, we would be glad to know the right way to follow.

Sincerely,

Thibaud.

**Comment by michael-lehn** [comment]
Hi Thibaud,

you are right!  Actually we need two wrappers (real and complex) for the case with internal workspace.  However, in your wrapper you loose the imaginary parts of the eigenvalues.  Even if A is a real matrix its eigenvalues can be complex.  And even if the eigenvalues for matrix A theoretically real, due to roundoff errors you might get complex eigenvalues.

So I would rather suggest:

``` C++
template <typename MA, typename VW>
typename RestrictTo<(IsRealGeMatrix<MA>::value
                  && IsRealDenseVector<VWR>::value,
                  && IsRealDenseVector<VWI>::value),
         typename RemoveRef<MA>::Type::IndexType>::Type
ev(MA       &&A,
   VWR      &&wr,
   VWI      &&wi)
{
    return ev(false, false, A, wr, wi, A, A);
}
```

**Comment by tkloczko** [comment]
Hi Michael,

Thanks a lot for this so fast answer :-) !

We implement your suggestion immediately !

Thanks again,

Thibaud,

PS : We actually use Flens to design 3D vectors and quaternions with our own Engine classes and additionnal operator (OpCross typically), I will tell you when it will be ready :-) !

**Comment by michael-lehn** [comment]
Wow, that sounds great!!
